--liquibase formatted sql
-- Database:postgresql

-- changeset anavarro:1

CREATE TABLE IF NOT EXISTS TRANSACTION_TYPES (
    ID VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    ID BIGINT NOT NULL,
    OPERATION_ID BIGINT NOT NULL,
    ACCOUNTING_DATE DATE,
    VALUE_DATE DATE,
    TRANSACTION_TYPE VARCHAR(255) NOT NULL REFERENCES TRANSACTION_TYPES(ID),
    AMOUNT BIGINT,
    DESCRIPTION VARCHAR(255),
    PRIMARY KEY(ID)
);


